# Informatics 2 - Foundations of Data Science
## Week S1 01: Introduction to Jupyter Notebooks and Pandas

**Learning outcomes:** 
In this lab you will learn the very basics of the Python library "pandas", which is used for data management. By the end of the lab you should be able to: 
- use a Jupyter notebook,
- load different data file types, 
- display data,
- filter your data for specific values, and 
- apply basic statistical computations on the data.

**Helpful background**  
- Basic knowledge of Python is helpful for this course. If you haven't used Python before or need a refresher there is a ["Getting Started with Python" lab sheet in Inf2-IADS](https://opencourse.inf.ed.ac.uk/inf2-iads/course-materials/semester-1/schedule). 
- Basic knowledge of NumPy is helpful for this course. NumPy provides data structures and functions for scientific computing on Python.  If you haven't used NumPy before or need a refresher, we can recommend the following [NumPy tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy). You may only need to do this when you get stuck.

We will try to cover a different research question every week. This week we will take the position of a historian and try to answer the following question.

**Research question:** Which passenger group had the worst survival rate on the [*Titanic*](https://en.wikipedia.org/wiki/Titanic)?

**Data information:** We will use a well-known dataset in the machine learning community, often referred to as the [titanic dataset](https://www.kaggle.com/c/titanic/data). It contains a list of passengers, information about whether they survived or not, and some extra information, such as age, fare, gender and the class they travelled in. On the website, you will find a testing and training dataset. What training data and testing data means will be covered later in this course. In this lab we will not be doing machine learning; therefore the data is combined into a single dataset.

## A. IPython / Jupyter environment

Jupyter Notebook is a web-based interactive computational environment, which enables code to be shared and documented. It supports Julia, Python and R (Ju-pyte-r). A notebook is a collection of *code* and *Markdown* (text) **cells**. 

Each code cell can be run separately, and the output is given below the cell. A number appears at the side of the *code* cell to indicate the order in which the cells were run. 

**Remarks**
1. Code in one cell can run, even if there are errors in other cells.
2. The order in which these cells are run is important, e.g. if you are calling a function in cell A, which is defined in cell B, cell B needs to be executed before cell A.
3. This means that the state of the variables in the notebook can be difficult to see.

All objects created by running cells are stored in the *kernel* running in the background. You can restart the kernel by using the Kernel menu at the top of the notebook. Because of the issues with the state of the system noted in the remarks, we recommend that when developing notebooks, you periodically select **Kernel->Restart Kernel & Run All Cells...** to check that your code really is reproducible. If you run into problems, it can also be a good idea to select **Kernel->Restart Kernel & Run All Cells...**; the problem might be due to the state of the variables.

### A.1 Basic operation and shortcuts

There are two modes of selection when inside a Jupyter Notebook:
1. Command Mode - When you hit up/down arrows you select different cells. Hit `<enter>` to enter edit mode.
2. Edit Mode - You can edit the cell. Hit `<esc>` to enter Command Mode again.

In Command Mode (cell highlighted blue):
```
          <enter> - Enter Edit Mode
              <a> - create new cell above selected
              <b> - create cell below selected
          <d> <d> - delete selected cell (pressing 'd' twice)
```

In Edit Mode (cell highlighted green):
```
            <esc> - Enter Command Mode
<shift> + <enter> - Run cell and move to cell below in Command Mode
 <ctrl> + <enter> - Run cell in place

```

Try running the following code cell:

In [1]:
a = 1
b = 2
a + b

3

You'll notice that the notebook will try to display the last thing in the cell, even if you don't use a `print` statement. However, if you want to print multiple things from one cell, you need to use multiple `print` statements (or multiple cells).

In [ ]:
first_name = "Jane"
last_name = "Doe"
print(first_name)
print(last_name)

**Good Practice** 
- It is good practice to separate code into different cells. One cell should correspond to one task, similarly to functions. For example, use a cell for the `import` statements, one for loading data, one for preprocessing data, and one for each different operation you carry out on the data.
- It's generally good practice to import all your packages at the top of a file. We will do so in future lab notebooks.

Before we start, we need to import the packages that we will be using later:

In [6]:
import os

import numpy as np
import pandas as pd

# Package to display the hints and soultions
from common.show_solutions import show

`os` stands for the standard Python operating system module, which we will use to access files. `pd` is an alias for the `pandas` module, to save typing later. Likewise `np` is an alias for NumPy module. `pd` and `np` are the standard aliases for `pandas` and NumPy.  Here is a more [in-depth tutorial on installing, importing and using modules](https://www.digitalocean.com/community/tutorials/how-to-import-modules-in-python-3).

## B. Pandas

Pandas is a library for data manipulation and analysis. There are two fundamental data structures in pandas: the **Series** and **DataFrame** structures which are built on top of NumPy arrays. (Again, if you need a refresher, you can check out this [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/#python).)

Pandas is [well documented](https://pandas.pydata.org/docs) and you will find good information about all methods and structures in the [API reference](https://pandas.pydata.org/docs/reference/index.html#api).

### B.1 Series

A **Series** is a one-dimensional object (similar to a list). Each element has a corresponding *index*. By default the indices range from `0` to `N-1`, where `N` is the length of the Series.

In [2]:
passenger = pd.Series(["Mr. Owen Harris Braund", 22.0, False])
passenger

0    Mr. Owen Harris Braund
1                      22.0
2                     False
dtype: object

It is generally a good idea to specify **meaningful labels for the index**. We can do so with the `index` parameter.

In [7]:
passenger = pd.Series(["Mr. Owen Harris Braund", 22.0, False], index=["Name", "Age", "Survived"])
passenger

Name        Mr. Owen Harris Braund
Age                           22.0
Survived                     False
dtype: object

You can **access a Series** entry the same way as you access list entries, using the assigned index labels such as `'Name'`.

In [8]:
print(passenger["Age"])  # Remember to use quotes

22.0

### B.2 DataFrame

A DataFrame is a tabular data structure comprised of rows and columns. You can also think of the DataFrame as a collection of Series objects that share an index. 

#### Creating DataFrame structures, adding rows, deleting rows and modifying entries

We can create an empty DataFrame by specifying the column names. Then we can insert data row by row.

In [9]:
passengers = pd.DataFrame(columns=["Gender", "Age", "Survived"])
passengers  # Careful, the dataframe is called passenger*s*, use meaningful variable names when coding

Empty DataFrame
Columns: [Gender, Age, Survived]
Index: []

Now, let's start filling the dataframe. To specify the row of a data frame, we use the `.loc` attribute.

In [10]:
passengers.loc[0] = ["Male", 22.0, False]  # Note how we used df.loc() to specify the index
passengers

  Gender   Age  Survived
0   Male  22.0     False

Remember, we said that a DataFrame is a collection of Series. Let's double check that.

In [13]:
type(passengers.loc[0])

pandas.Series

Pandas DataFrames are quite flexible. Just as with Series, we can also use strings as index labels.

In [14]:
passengers.loc["Mrs. John Bradley Cumings"] = ["Female", 38.0, "Yes"]
passengers

                           Gender   Age Survived
0                            Male  22.0    False
Mrs. John Bradley Cumings  Female  38.0      Yes

**Remark:** It is generally bad practice to mix different kinds of indices. So let's remove the first entry.

In [15]:
cleaned_passengers = passengers.drop(0)
print(cleaned_passengers)
print("\n")  # Empty line between DataFrames
print(passengers)

                           Gender   Age Survived
Mrs. John Bradley Cumings  Female  38.0      Yes


                           Gender   Age Survived
0                            Male  22.0    False
Mrs. John Bradley Cumings  Female  38.0      Yes

**Remark**: By default, `df.drop(index)` creates a copy of the DataFrame without modifying the original DataFrame, which is why if you want to drop a row without creating a new DataFrame, you need to write `df = df.drop(0, inplace=True)`, i.e. set the optional `inplace` argument to `True`. You can see the difference between `cleaned_passengers` and `passengers` above.

In [16]:
passengers.drop(0, inplace=True)  # Remove the 0th passenger without creating a copy
passengers

                           Gender   Age Survived
Mrs. John Bradley Cumings  Female  38.0      Yes

You can also populate a DataFrame using a dictionary which allows you to do things in a nonstandard order. Let's get our first entry back.

In [17]:
passengers.loc["Mr. Owen Harris Braund"] = dict(
    Survived=False, Age=22.0, Gender="Male"
)  # Notice that the attributes are assigned in a different order
passengers

                           Gender   Age Survived
Mrs. John Bradley Cumings  Female  38.0      Yes
Mr. Owen Harris Braund       Male  22.0    False

We just made a mess. In the first row, we used a string to denote whether the passenger survived, and in the second a Boolean value. Let's clean this up.

In [18]:
passengers.loc["Mrs. John Bradley Cumings", "Survived"] = True
passengers

                           Gender   Age Survived
Mrs. John Bradley Cumings  Female  38.0     True
Mr. Owen Harris Braund       Male  22.0    False

#### Creating DataFrame from other structures

You can also create a DataFrame from:
* A dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

Let's recreate the same DataFrame:

In [19]:
# Create a DataFrame from a list
passengers_list = [["Male", 22.0, False], ["Female", 38.0, True]]
passengers = pd.DataFrame(
    passengers_list,
    index=["Mr. Owen Harris Braund", "Mrs. John Bradley Cumings"],
    columns=["Gender", "Age", "Survived"],
)
passengers

                           Gender   Age  Survived
Mr. Owen Harris Braund       Male  22.0     False
Mrs. John Bradley Cumings  Female  38.0      True

In [20]:
# Create a DataFrame from a dictionary where keys are column values
column_key_dict = {"Gender": ["Male", "Female"], "Age": [22.0, 38.0], "Survived": [False, True]}
passengers = pd.DataFrame.from_dict(column_key_dict, orient="columns")
passengers.index = ["Mr. Owen Harris Braund", "Mrs. John Bradley Cumings"]
passengers

                           Gender   Age  Survived
Mr. Owen Harris Braund       Male  22.0     False
Mrs. John Bradley Cumings  Female  38.0      True

In [21]:
# Create a DataFrame from a dictionary where keys are index values
index_key_dict = {"Mr. Owen Harris Braund": ["Male", 22.0, False], "Mrs. John Bradley Cumings": ["Female", 38.0, True]}
passengers = pd.DataFrame.from_dict(index_key_dict, orient="index")
passengers.columns = ["Gender", "Age", "Survived"]
passengers

                           Gender   Age  Survived
Mr. Owen Harris Braund       Male  22.0     False
Mrs. John Bradley Cumings  Female  38.0      True

In [22]:
# Using the DataFrame call, keys are assumed to be column headers
passengers = pd.DataFrame(
    {"Mr. Owen Harris Braund": ["Male", 22.0, False], "Mrs. John Bradley Cumings": ["Female", 38.0, True]},
    index=["Gender", "Age", "Survived"],
)
passengers

         Mr. Owen Harris Braund Mrs. John Bradley Cumings
Gender                     Male                    Female
Age                        22.0                      38.0
Survived                  False                      True

However, now the rows have become columns and vice versa. We could rewrite the code above, assigning the passenger names to the `index` argument, and using the Gender, Age and Survived attributes as the dict keys. However, there is a more elegant solution: we can use the transpose method `df.T`

In [23]:
passengers = passengers.T
passengers

                           Gender   Age Survived
Mr. Owen Harris Braund       Male  22.0    False
Mrs. John Bradley Cumings  Female  38.0     True

**Remark** Again, the transpose method creates a copy. Thus, if you want to actually apply the changes to the DataFrame, you need to save it to the variable, as shown above.

Let's combine a few things we have learned so far.

**Exercise 01a:** 
- Delete the markdown cell below, which says 'We don't need this cell.'.
- Insert a new code cell below this cell.
- Create a 'passengers' DataFrame with one of the options we have presented above, which contains the following entries: 
    - Miss. Laina Heikkinen, Female, aged 26, survived; 
    - Mrs. Jacques Heath Futrelle, Female, 35 years old, survived;
    - Mr. William Henry Allen, male, 35.0, did not survive;
- Make sure that you use a consistent notation in your DataFrame.

In [31]:
passengers_dict = {"Miss. Laina Heikkinen": ["Female", 26, True],
                   "Mrs. Jacques Heath Futrelle": ["Female", 35, True],
                   "Mr. William Henry Allen": ["Male", 35, False]}
passengers = pd.DataFrame.from_dict(passengers_dict, orient="index")
passengers

                                  0   1      2
Miss. Laina Heikkinen        Female  26   True
Mrs. Jacques Heath Futrelle  Female  35   True
Mr. William Henry Allen        Male  35  False

In [ ]:
# Run this cell to be offered with hints and solution
show(week=1, question=1)

**Exercise 01b:**
- Append the two passengers mentioned previously (Mr. Own Harris Braund and Mrs. John Bradley Cumings) to the DataFrame.

In [ ]:
# Run this cell to be offered with hints and solution
show(week=1, question=2)

In [32]:
new_passengers_dict = {"Mr. Owen Harris Braund": ["Male", 22, False],
                       "Mrs. John Bradley Cumings": ["Female", 22, True]}
new_passengers = pd.DataFrame.from_dict(new_passengers_dict, orient="index")
passengers = pd.concat([passengers, new_passengers])
passengers

                                  0   1      2
Miss. Laina Heikkinen        Female  26   True
Mrs. Jacques Heath Futrelle  Female  35   True
Mr. William Henry Allen        Male  35  False
Mr. Owen Harris Braund         Male  22  False
Mrs. John Bradley Cumings    Female  22   True

### B.3 Reading data into Pandas

__At this point we suggest driver and navigator swap over again.__ 

Most commonly we create DataFrame structures by reading CSV (Comma Separated Variable) files. The datasets needed in this notebook (and subsequent notebooks) are in the `datasets` folder.

In [33]:
passengers_filepath = os.path.join(os.getcwd(), "datasets", "titanic.csv")
passengers_filepath

'/Users/liamriley/Projects/fds-labs/s1-01/datasets/titanic.csv'

In [61]:
passengers = pd.read_csv(passengers_filepath)
passengers.head()  # Head shows the first five elements (unless specified otherwise) of the DataFrame

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

These are the five passengers you should have added to your dataframe in Exercise 01. Now, we have some extra information. Using `df.head()` we can get an impression of how the data looks like in our dataset. Note that the information in the Survived column is stored as 0/1 instead of `False/True`. Pandas doesn't care how Boolean values are stored. If a column only contains 0s and 1s, Pandas treats the column as Boolean, and works with it in the same way as a column of `False` and `True`.

However, `df.head()` only shows the first five entries. How many entries are there in total? You can use the Python native `len()` function.

In [35]:
len(passengers)

887

#### Tab completion

Tab completion is a powerful method for viewing object attributes and available methods.

We have just seen the `df.head()` method above. Let's see what other functions we can call on a DataFrame. You can see what methods are available by typing the DataFrame name followed by `.` and then hitting the `<tab>` key. Then you can access any function or method's help documentation by either pressing `<shift>-<tab>` or by typing `?` after the method's name and then `<return>`

For example, to find the last few entries of the DataFrame, first type `passengers.t`, then hit `<tab>` and then choose `df.tail()`.

In [ ]:
passengers.take()

In [ ]:
# Let's get the documentation with <shift>-<tab>
passengers.tail

If you want to get more than five entries you can do so by specifying `N` entries with `df.head(N)` or `df.tail(N)`. Give it a try above.

### B.4 Selecting rows and columns

#### Row selection

As already mentioned, you can think of a DataFrame as a group of Series that share an index (*either* the column headers or the row id). This makes it easy to select specific **observations (i.e. rows)**.

In [36]:
type(passengers.loc[0])

pandas.Series

We have already talked about `df.loc[label]`, which selects a row based on the label of the index, e.g. 'Mr. Owen Harris Braund'. If we want the N-th row, we can use `df.iloc[N]`. In the loaded Titanic dataset, it so happens that the indices also run from 0 to 886, and thus `df.loc[N]` and `df.iloc[N]` return the same observation.

Technically, there are three options to select rows:
* `df.loc[label]`: works on labels in the index
* `df.iloc[N]`: works on the position in the index (so it only takes integers)
* `df[N]`: works the same way as `df.iloc[N]`

It is often safest to use the first two methods (rather than just using square brackets) to index into pandas DataFrames.

In [37]:
passengers.iloc[0]

Survived                                        0
Pclass                                          3
Name                       Mr. Owen Harris Braund
Sex                                          male
Age                                          22.0
Siblings/Spouses Aboard                         1
Parents/Children Aboard                         0
Fare                                         7.25
Name: 0, dtype: object

We can also select several rows; the resulting structure is a DataFrame. This operation is called **slicing**.

**Remark:** Python slicing might seem a bit confusing. When you specify a range to slice with `i:j` the slice returned runs from the `i`-th entry to the `j-1`-th entry. This can be very helpful at times, when you want the last few entries, and you don't know how long the object is (e.g. a DataFrame or list). In that case, you can slice with `k:len(object)`.

In [ ]:
type(passengers.iloc[0:3])

In [ ]:
passengers.iloc[0:3]

In [ ]:
# This is equivalent to using .iloc
passengers[0:3]

#### Column Selection

As already mentioned, you can think of a DataFrame as a group of Series that share an index (*either* the column headers or the row id). This makes it as easy to select specific **columns** as it is to select rows.

In [38]:
type(passengers["Name"])

pandas.Series

In [39]:
passengers["Name"].head()

0                               Mr. Owen Harris Braund
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                Miss. Laina Heikkinen
3          Mrs. Jacques Heath (Lily May Peel) Futrelle
4                              Mr. William Henry Allen
Name: Name, dtype: str

To select multiple columns we simply need to pass a list of column names. We said above that we were interested in who survived, so let's check that:

In [40]:
# Remark the double brackets, because we passed a list of names
passengers[["Name", "Survived"]].head(7)

                                                Name  Survived
0                             Mr. Owen Harris Braund         0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...         1
2                              Miss. Laina Heikkinen         1
3        Mrs. Jacques Heath (Lily May Peel) Futrelle         1
4                            Mr. William Henry Allen         0
5                                    Mr. James Moran         0
6                             Mr. Timothy J McCarthy         0

**Exercise 02:** What do you expect what the type of `passengers[['Name', 'Survived']].head(7)` is? Check it!

In [42]:
type(passengers[["Name", "Survived"]])

pandas.DataFrame

You can combine row and column selection, as we already did above, when selecting a specific entry.

In [43]:
passengers.iloc[0]["Survived"]

0

**Exercise 03:** Look at the dataframe you obtained in Exercise 01. Reconstruct the same dataframe using the newly loaded dataframe, i.e. select the correct rows and columns, such that the output is the same as in Exercise 01.

In [ ]:
# Run this cell to be offered with hints and solution
show(week=1, question=3)

In [46]:
passengers.iloc[0:5][['Name', 'Sex', 'Age', 'Survived']]

                                                Name     Sex   Age  Survived
0                             Mr. Owen Harris Braund    male  22.0         0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0         1
2                              Miss. Laina Heikkinen  female  26.0         1
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0         1
4                            Mr. William Henry Allen    male  35.0         0

### B.5 Filtering

Now suppose that you want to select all the observations of minors (i.e. people under the age of 18 in the UK). It is easy to do that:

In [49]:
passengers[passengers["Age"] <= 17]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7000
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
16,0,3,Master. Eugene Rice,male,2.0,4,1,29.1250
...,...,...,...,...,...,...,...,...
849,1,1,Miss. Mary Conover Lines,female,16.0,0,1,39.4000
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
865,1,3,Master. Harold Theodor Johnson,male,4.0,1,1,11.1333
871,1,3,Miss. Adele Kiamie Najib,female,15.0,0,0,7.2250
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

Or equivalently:

In [ ]:
passengers[passengers.Age <= 17]

This concept is called *filtering*, and `passengers.Age <= 17` is called a **mask**, which hides/masks all entries that don't fit the criteria; i.e. it only returns the observations for which the mask returns `True`. You can also filter the data by using multiple attributes:

In [50]:
young_passengers = passengers[(passengers.Age <= 17) & (passengers.Survived)]  # We were able to drop 'Survived == 1'
young_passengers

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.00,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.00,1,1,16.7000
22,1,3,Miss. Anna McGowan,female,15.00,0,0,8.0292
39,1,3,Miss. Jamila Nicola-Yarred,female,14.00,1,0,11.2417
42,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3.00,1,2,41.5792
...,...,...,...,...,...,...,...,...
826,1,3,Mrs. Antoni (Selini Alexander) Yasbeck,female,15.00,1,0,14.4542
827,1,2,Master. George Sibley Richards,male,0.83,1,1,18.7500
849,1,1,Miss. Mary Conover Lines,female,16.00,0,1,39.4000
865,1,3,Master. Harold Theodor Johnson,male,4.00,1,1,11.1333
871,1,3,Miss. Adele Kiamie Najib,female,15.00,0,0,7.2250

**Remark** The first row has index 9. As mentioned earlier: the label of the index does not have to coincide with the position of the data entry. Here, `df.iloc[9]` and `df.loc[9]` return different values!

**You may wish to swap driver and navigator at this point.**

**Exercise 04:** What will be the return values of `young_passengers.iloc[8:10]` and `young_passengers.loc[8:10]`. Check the answer.

In [54]:
young_passengers.loc[8:10]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7000

Note that we can also index into columns using `loc`. We just have to specify the second dimension (much as we would do with NumPy arrays). Let's give it a try. We want to get the list of minors (children) aboard the *Titanic*:

In [55]:
young_passengers.loc[:, "Name"]

9           Mrs. Nicholas (Adele Achem) Nasser
10              Miss. Marguerite Rut Sandstrom
22                          Miss. Anna McGowan
39                  Miss. Jamila Nicola-Yarred
42     Miss. Simonne Marie Anne Andree Laroche
                        ...
826     Mrs. Antoni (Selini Alexander) Yasbeck
827             Master. George Sibley Richards
849                   Miss. Mary Conover Lines
865             Master. Harold Theodor Johnson
871                   Miss. Adele Kiamie Najib
Name: Name, Length: 65, dtype: str

In [56]:
young_passengers.iloc[:, 2]  # And now using column indexing **Remark** this would not work with .loc[:, 2]

9           Mrs. Nicholas (Adele Achem) Nasser
10              Miss. Marguerite Rut Sandstrom
22                          Miss. Anna McGowan
39                  Miss. Jamila Nicola-Yarred
42     Miss. Simonne Marie Anne Andree Laroche
                        ...
826     Mrs. Antoni (Selini Alexander) Yasbeck
827             Master. George Sibley Richards
849                   Miss. Mary Conover Lines
865             Master. Harold Theodor Johnson
871                   Miss. Adele Kiamie Najib
Name: Name, Length: 65, dtype: str

In [58]:
# If we try the following we will get an empty DataFrame because there are no rows with labels 0 and 1.
young_passengers.loc[0:2]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, Siblings/Spouses Aboard, Parents/Children Aboard, Fare]
Index: []

In [59]:
# The result is still a DataFrame
type(young_passengers.loc[0:2])

pandas.DataFrame

For more, check out [Advanced Indexing](http://pandas.pydata.org/pandas-docs/version/0.23.4/advanced.html)

### B.6 Summary and final exercise

We now know how to 
- load a dataset from a csv file `pd.read_csv()`, 
- get the first few entries `df.head()`, 
- select certain rows or columns based on their position `df.iloc[]` or index label `df.loc[]`,
- and finally how to filter the dataset for entries that satisfy certain conditions `df[condition]`.

However, at the beginning of the lab, we wanted to figure out the passenger group worst hit. Using filtering, we can already split the dataset into different subsets. Now let's apply some operations.

First let's get the age spread, and figure out the oldest and youngest passenger. The passengers in the dataset are not sorted by age. Looking at each entry individually is not an option. Thankfully pandas dataframes have a method: `df.sort_values(by='column', ascending={True,False})`.

In [62]:
passengers.sort_values(by="Age").head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
799,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
827,1,2,Master. George Sibley Richards,male,0.83,1,1,18.7500

In [63]:
passengers.sort_values(by="Age", ascending=False).head()  # Returns the data in descending order of the sorted value

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500

The two results above already show that young passengers had a better survival rate than senior passengers. Let's try, tentatively, to answer the research question.  

**Discussion:** We will consider the different travel classes, genders, and age groups. Discuss with your lab partner who you would expect had the best and who had the worst survival rate. 

**Exercise 05:**

- **a.** Compute the survival rate of: minors (0-17 years old), adults (18-65), and seniors (66+).
- **b.** Compute the survival rate of: women and men.
- **c.** Compute the survival rate of the travel classes (1, 2, and 3).
- **d.** Does the gender have an influence on the survival rates of minors? (What is the survival rate of girls vs boys?)
- **e.** Compute the survival rate of all combinations of class, age group, and gender, and print them out as "Age group, gender, class: percentage", e.g. "Minors, Male, First Class: 0.3".

In [4]:
# Run this cell to be offered with hints and solution
show(week=1, question=5)

Tab(children=(Accordion(children=(Output(layout=Layout(border_bottom='1px solid blue', border_left='1px solid …

In [92]:
# Your Code

def calculate_survival_rate(population_group):
    return len(population_group[population_group["Survived"] ==1 ]) / len(population_group)


# Exercise a
minors = passengers[passengers["Age"] < 18]
adults = passengers[(passengers["Age"] >= 18) & (passengers["Age"] < 66)]
seniors = passengers[passengers["Age"] >= 66]


print(calculate_survival_rate(minors))
print(calculate_survival_rate(adults))
print(calculate_survival_rate(seniors))
print("The younger the passenger, the higher the survival rate.")

print("-"*50)

# Exercise b
women = passengers[passengers["Sex"] == "female"]
men = passengers[passengers["Sex"] == "male"]

print(calculate_survival_rate(women))
print(calculate_survival_rate(men))
print("Women were much more likely to survive than men.")

print("-"*50)

# Exercise c

class_one = passengers[passengers["Pclass"] == 1]
class_two = passengers[passengers["Pclass"] == 2]
class_three = passengers[passengers["Pclass"] == 3]

print(calculate_survival_rate(class_one))
print(calculate_survival_rate(class_two))
print(calculate_survival_rate(class_three))
print("The more expensive your ticket, the more likely you were to survive.")

print("-"*50)

# Exercise d
minors_boys = minors.merge(men, how="inner")
minors_girls = minors.merge(women, how="inner")

print(calculate_survival_rate(minors_boys))
print(calculate_survival_rate(minors_girls))
print("Girls were much more likely to survive than boys.")

print("-"*50)

# Exercise e

0.5
0.36947791164658633
0.1
--------------------------------------------------
0.7420382165605095
0.19022687609075042
--------------------------------------------------
0.6296296296296297
0.47282608695652173
0.24435318275154005
--------------------------------------------------
0.373134328358209
0.6349206349206349
--------------------------------------------------

In [85]:
minors_boys

,Survived_x,Pclass_x,Name,Sex_x,Age_x,Siblings/Spouses Aboard_x,Parents/Children Aboard_x,Fare_x,Survived_y,Pclass_y,Sex_y,Age_y,Siblings/Spouses Aboard_y,Parents/Children Aboard_y,Fare_y
0,0,3,Master. Gosta Leonard Palsson,male,2.00,3,1,21.0750,0,3,male,2.00,3,1,21.0750
1,0,3,Master. Eugene Rice,male,2.00,4,1,29.1250,0,3,male,2.00,4,1,29.1250
2,0,3,Mr. Youssef Samaan,male,16.00,2,0,21.6792,0,3,male,16.00,2,0,21.6792
3,0,3,Master. Juha Niilo Panula,male,7.00,4,1,39.6875,0,3,male,7.00,4,1,39.6875
4,0,3,Master. William Frederick Goodwin,male,11.00,5,2,46.9000,0,3,male,11.00,5,2,46.9000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,1,2,Master. George Sibley Richards,male,0.83,1,1,18.7500,1,2,male,0.83,1,1,18.7500
63,0,2,Mr. Thomas Charles Mudd,male,16.00,0,0,10.5000,0,2,male,16.00,0,0,10.5000
64,0,3,Mr. Jeso Culumovic,male,17.00,0,0,8.6625,0,3,male,17.00,0,0,8.6625
65,0,3,Master. Sigvard Harald Elias Andersson,male,4.00,4,2,31.2750,0,3,male,4.00,4,2,31.2750
66,1,3,Master. Harold Theodor Johnson,male,4.00,1,1,11.1333,1,3,male,4.00,1,1,11.1333

## Pair programmers: How to share your files with each other


At the end of the session you will probably want to share the actual file (not just access to each other's Noteable). A simple (but not elegant) method is to download the file and email it to each other. To download a file from this  notebook, select: __File→Download__.

When you share access to your Noteable, as in this notebook, you and your partner will be logged in with your account. You should both "log out" when you stop working together. To do this, you can stop the Jupyter server by:
1. Going back to the Jupyter file browser
2. Clicking on the __Noteable__ icon at the top right
3. On the next screen, clicking on __Shutdown__
You can then close the browser tab.